version: 1
labels:
  # Docs
  - label: "documentation"
    title: '^(?:[Dd][Oo][Cc][Ss])(?:\b|:|\s|$)'
  # Bugs and fixes
  - label: "bug"
    title: '^(?:[Bb][Uu][Gg](?:[Ff][Ii][Xx])?|[Hh][Oo][Tt][Ff][Ii][Xx]|[Ff][Ii][Xx])(?:\b|:|\s|$)'
  # Features
  - label: "feature"
    title: '^(?:[Ff][Ee][Aa][Tt]|[Ff][Ee][Aa][Tt][Uu][Rr][Ee])(?:\b|:|\s|$)'
  # UI
  - label: "ui"
    title: '^(?:[Uu][Ii])(?:\b|:|\s|$)'
  # Formatting
  - label: "style"
    title: '^(?:[Ff][Oo][Rr][Mm][Aa][Tt]|[Ss][Tt][Yy][Ll][Ee])(?:\b|:|\s|$)'
  # Refactors
  - label: "refactor"
    title: '^(?:[Rr][Ee][Ff][Aa][Cc][Tt]|[Rr][Ee][Ff][Aa][Cc][Tt][Oo][Rr])(?:\b|:|\s|$)'
  # Tests
  - label: "test"
    title: '^(?:[Tt][Ee][Ss][Tt])(?:\b|:|\s|$)'
  # Work in progress
  - label: "work in progress"
    title: '^(?:[Ww][Ii][Pp])(?:\b|:|\s|$)'
  # Experiments
  - label: "experiment"
    title: '^(?:[Ee][Xx][Pp]|[Ee][Xx][Pp][Ee][Rr][Ii][Mm][Ee][Nn][Tt])(?:\b|:|\s|$)'
  # Miscellaneous
  - label: "miscellaneous"
    title: '^(?:[Mm][Ii][Ss][Cc])(?:\b|:|\s|$)'
  # Tasks
  - label: "task"
    title: '^(?:[Tt][Aa][Ss][Kk])(?:\b|:|\s|$)'
