name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: >-
          Thanks for opening your first issue on this repository! Make sure you've read our
          [contributing guidelines](https://github.com/TheGittyPerson/ThePerson/blob/main/.github/CONTRIBUTING.md)
          — it's very important to us.
          
          Key things to remember when contributing to this repo:
            - Avoid touching others' code when possible
            - **Rebase > Merge**; When updating your PR branch, always use a rebase and resolve conflicts
            - Try to follow PEP 8
            - Avoid using AI to generate code, comments, or issue/PR descriptions

        pr-message: >-
          Thanks for opening your first PR on this repository! Make sure you've read our 
          [contributing guidelines](https://github.com/TheGittyPerson/ThePerson/blob/main/.github/CONTRIBUTING.md)
          — it's very important to us.
          
          Key things to remember when contributing to this repo:
            - Avoid touching others' code when possible
            - **Rebase > Merge**; When updating your PR branch, always use a rebase and resolve conflicts
            - Try to follow PEP 8
            - Avoid using AI to code, comments, or issue/PR descriptions
