name: PR Labeler
on:
  pull_request_target:
    types: [opened, reopened, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: read
    steps:
      - name: Label based on title
        uses: srvaroa/labeler@v1
        with:
          config_path: .github/labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
