name: Stale Issues/PR Marker

on:
  schedule:
  - cron: '00 00 * * *'
  workflow_dispatch:

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-issue-stale: 21
        days-before-pr-stale: 14
        exempt-issue-labels: "pinned,security,in-progress"
        exempt-pr-labels: "pinned,security,in-progress"
        stale-issue-message: |
          This issue has been inactive for some time, and will therefore be marked as 'stale'.
          Tag a maintainer if you wish to discuss this further.
        stale-pr-message: |
          This pull request has been inactive for some time, and will therefore be marked as 'stale'.
          Tag a maintainer if you wish to discuss this further.
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
